- name: General tasks
  block:
    - import_tasks: os-tasks/system-update.yml
    - import_tasks: os-tasks/banners.yml
    - import_tasks: os-tasks/permissions-for-root-home-directory.yml
    - import_tasks: os-tasks/disable-nfs.yml
    - import_tasks: os-tasks/disable-smb-nmb-services.yml
    - import_tasks: os-tasks/diffie-hellmann-moduli-hardening.yml
    - import_tasks: os-tasks/enable-sysstat.yml
    - import_tasks: os-tasks/disable-usb-mass-storage.yml
    - import_tasks: os-tasks/disable-firewire-ohci-driver.yml
    - import_tasks: os-tasks/postfix-set-banner.yml
    - import_tasks: os-tasks/core-dumps-disable.yml
    - import_tasks: os-tasks/permissions-on-critical-files.yml
    - import_tasks: os-tasks/rkhunter-install.yml
    - import_tasks: os-tasks/expire-dates-for-password-protected-accounts.yml
    - import_tasks: os-tasks/linux-mountpoints-hardening.yml
    - import_tasks: os-tasks/umask-set-on-profile-files.yml
    - import_tasks: os-tasks/set-hidepid-to-users.yml
    - import_tasks: os-tasks/session-timeout.yml
    - import_tasks: os-tasks/hosts-file-setup.yml
    - import_tasks: os-tasks/world-writeable-paths.yml
    - import_tasks: os-tasks/uninstall-unnecessary-packages.yml
    - import_tasks: os-tasks/audit-log-files-on-a-regular-basis.yml
    - import_tasks: os-tasks/disable-storage-of-bash-history.yml
    - import_tasks: os-tasks/set-defaults-env_reset.yml
    - import_tasks: os-tasks/unauthorized-UID-0-accounts.yml
    - import_tasks: os-tasks/accounts-without-password.yml
    - import_tasks: os-tasks/home-directory-permissions.yml
    - import_tasks: os-tasks/uninstall-insecure-packages.yml
    - import_tasks: os-tasks/use-minimal-number-of-sudo-accounts.yml
    - import_tasks: os-tasks/set-inactive-period-in-useradd-file.yml
    - import_tasks: os-tasks/lock-default-service-accounts.yml
    - import_tasks: os-tasks/login.defs-hardening.yml
    - import_tasks: os-tasks/set-compiler-permissions.yml
  tags: global-tasks

- name: OS-family related tasks
  block:
    - include_tasks: "related-to-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  tags: os-related-tasks

- name: Audit scan
  block:
    - import_tasks: os-tasks/lynis-audit-scan.yml
  tags: audit-scan