    - name: Check accounts without password
      shell: |
        cat /etc/shadow | awk -F':' '$2 !~ /^\!/  {print }' \
                        | awk -F':' '$2 !~ /^\*/  {print }' \
                        | awk -F':' '$2 !~ /^x/   {print }' \
                        | awk -F':' '$2 !~ /^\$6/ {print }' \
                        | awk -F':' '$2 !~ /^\$2/ {print }'
      register: account_without_pass
      changed_when: account_without_pass.stdout|length > 0
      failed_when: false
      notify: Accounts without password

    - meta: flush_handlers