    - name: Audit log files on a regular basis
      block:
        - name: Audit log files on a regular basis (CHMOD 0640 in /var/log)
          shell: |
            find /var/log        -type f -perm /0137 -name "boot.log" 2>/dev/null; \
            find /var/log        -type f -perm /0137 -name "messages" 2>/dev/null; \
            find /var/log        -type f -perm /0137 -name "syslog*"  2>/dev/null; \
            find /var/log/syslog -type f -perm /0137                  2>/dev/null; \
            find /var/log        -type f -perm /0137 -name "auth.log" 2>/dev/null; \
            find /var/log        -type f -perm /0137 -name "secure"   2>/dev/null; \
            find /var/log        -type f -perm /0137 -name "dmesg"    2>/dev/null; \
            find /var/log        -type f -perm /0137 -name "kern.log" 2>/dev/null; \
            find /var/log        -type f -perm /0137 -name "faillog"  2>/dev/null; \
            find /var/log        -type f -perm /0137 -name "cron"     2>/dev/null; \
            find /var/log        -type f -perm /0137 -name "yum.log"  2>/dev/null; \
            find /var/log        -type f -perm /0137 -name "mail*"    2>/dev/null; \
            find /var/log/httpd  -type f -perm /0137                  2>/dev/null; \
            find /var/log        -type f -perm /0137 -name "mysql*"   2>/dev/null; \
            find /var/log        -type f -perm /0137 -name "apache*"  2>/dev/null
          register: candidates_0640
          changed_when: candidates_0640.stdout | length > 0
          notify: Set CHMOD 0640 on log files
        - name: Audit log files on a regular basis (CHMOD 0660 in /var/log)
          shell: |
            find /var/log -type f -perm /0117 -name "pacemaker.log"   2>/dev/null; \
            find /var/log -type f -perm /0117 -name "pacemaker.log-*" 2>/dev/null; \
            find /var/log -type f -perm /0117 -name "nsclient.log*"   2>/dev/null
          register: candidates_0660
          changed_when: candidates_0660.stdout | length > 0
          notify: Set CHMOD 0660 on log files
        - name: Audit log files on a regular basis (CHMOD 0733 in /var/log)
          shell: find /var/log -type d -perm /0044 -name "sudosh" 2>/dev/null
          register: candidates_0733
          changed_when: candidates_0733.stdout | length > 0
          notify: Set CHMOD 0733 on log files
        - name: Audit log files on a regular basis (CHMOD 0664 in /var/log)
          shell: find /var/log -type f -perm /0113 -name "wtmp" 2>/dev/null
          register: candidates_0664
          changed_when: candidates_0664.stdout | length > 0
          notify: Set CHMOD 0664 on log files
        # CRONTAB setup ############################################################
        - name: Setup crontab to audit log files automatically, to avoid manual work
          block:
            - name: Copy crontab script to the remote host
              copy:
                src: files/audit-log-files.sh.j2
                dest: /usr/local/sbin/audit-log-files.sh
                owner: root
                group: root
                mode: '0700'
            - name: Setup crontab to automatically fix log file permissions
              cron:
                name: "Audit log files on a regular basis"
                minute: "20"
                hour: "07"
                state: present
                job: "/usr/local/sbin/audit-log-files.sh > /tmp/audit-log-files.sh.log"
            - name: Set logrotate rule for the log generated by a crontab
              copy:
                content: |
                  /var/log/log-permissions-backup.log {
                    weekly
                    rotate 15
                    size 50M
                    notifempty
                    copytruncate
                    missingok
                    dateext
                  }
                dest: /etc/logrotate.d/audit-log-permissions
                owner: root
                group: root
                mode: '0644'

    - meta: flush_handlers