    - name: Check if audit rules are exists
      shell: auditctl -l
      register: audit_check
      changed_when: '"No rules" in audit_check.stdout'
      notify: Setup audit (SLES)

    - meta: flush_handlers
