    - name: Set hashing rounds for new passwords
      shell: |
        pam-config -a  --unix-rounds=900000
      register: rounds
      changed_when: rounds.stdout|length > 0
      notify: Change password (message)

    - meta: flush_handlers