    - name: Set hashing rounds for new passwords
      shell: |
        if [[ $(grep 'rounds=' /etc/pam.d/system-auth | grep "password" | grep -c pam_unix.so) -eq 0 ]]; then
          echo "Based on the https://access.redhat.com/solutions/1519833"
          cd /etc/pam.d
          cp -v system-auth system-auth-rounds
          ln -svf system-auth-rounds system-auth
          sed --follow-symlinks -ri "/^password\s+sufficient\s+pam_unix.so/s, rounds=[0-9]+|$, rounds=900000,"  /etc/pam.d/system-auth
        fi
      register: rounds
      changed_when: rounds.stdout|length > 0
      notify: Change password (message)

    - meta: flush_handlers
