    - name: Set expire dates for all password protected accounts -> List users with password
      shell: |
        awk -F: '($2 ~ /^\$/) {print $1}' /etc/shadow
      register: users_passwd
      changed_when: false

    - name: Set expire dates for all password protected accounts -> Set expire dates
      shell: |
        PASS_MAX_DAYS=$(passwd -S {{ item }} | awk '{print $5}')
        if [[ ${PASS_MAX_DAYS} -gt 180 ]]; then
          echo "PASSWD_MAX_DAYS is not correct"
          chage --lastday $(date '+%Y-%m-%d') {{ item }}
          chage --expiredate $(date -d +180days +%Y-%m-%d) {{ item }}
          chage --maxdays 180 {{ item }}
        fi
      with_items:
        - "{{ users_passwd.stdout_lines }}"
      register: set_dates
      changed_when: set_dates.stdout|length > 0