    - name: Kernel Hardening
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        reload: yes
        state: present
        sysctl_set: yes
      loop:
        - { name: 'fs.protected_fifos', value: '2' }
        - { name: 'fs.protected_hardlinks', value: '1' }
        - { name: 'fs.protected_regular', value: '2' }
        - { name: 'fs.protected_symlinks', value: '1' }
        - { name: 'fs.suid_dumpable', value: '0' }
        - { name: 'kernel.core_uses_pid', value: '1' }
        - { name: 'kernel.ctrl-alt-del', value: '0' }
        - { name: 'kernel.dmesg_restrict', value: '1' }
        - { name: 'kernel.kptr_restrict', value: '2' }
        - { name: 'kernel.perf_event_paranoid', value: '3' }
        - { name: 'kernel.randomize_va_space', value: '2' }
        - { name: 'kernel.sysrq', value: '0' }
        - { name: 'kernel.unprivileged_bpf_disabled', value: '1' }
        - { name: 'kernel.yama.ptrace_scope', value: '1' }
        - { name: 'net.core.bpf_jit_harden', value: '2' }
        - { name: 'net.ipv4.conf.all.accept_redirects', value: '0' }
        - { name: 'net.ipv4.conf.all.accept_source_route', value: '0' }
        - { name: 'net.ipv4.conf.all.bootp_relay', value: '0' }
        - { name: 'net.ipv4.conf.all.forwarding', value: '0' }
        - { name: 'net.ipv4.conf.all.log_martians', value: '1' }
        - { name: 'net.ipv4.conf.all.proxy_arp', value: '0' }
        - { name: 'net.ipv4.conf.all.rp_filter', value: '1' }
        - { name: 'net.ipv4.conf.all.send_redirects', value: '0' }
        - { name: 'net.ipv4.conf.default.accept_redirects', value: '0' }
        - { name: 'net.ipv4.conf.default.accept_source_route', value: '0' }
        - { name: 'net.ipv4.conf.default.log_martians', value: '1' }
        - { name: 'net.ipv4.icmp_echo_ignore_broadcasts', value: '1' }
        - { name: 'net.ipv4.icmp_ignore_bogus_error_responses', value: '1' }
        - { name: 'net.ipv4.tcp_syncookies', value: '1' }
        - { name: 'net.ipv4.tcp_timestamps', value: '1' }
        - { name: 'net.ipv6.conf.all.accept_redirects', value: '0' }
        - { name: 'net.ipv6.conf.all.accept_source_route', value: '0' }
        - { name: 'net.ipv6.conf.default.accept_redirects', value: '0' }
        - { name: 'net.ipv6.conf.default.accept_source_route', value: '0' }
