    - name: Lock default services accounts
      shell: |
         SERVICE_ACCOUNTS="$(
           grep -Ev "/(.*)bin/nologin$" /etc/passwd | \
           grep -Ev "/(.*)bin/false$" | \
           awk -F: '($3 < 200 && $3>=1) && $2 != "*" { print $1 }'
         )"
         # LOCK ----------
         for i in ${SERVICE_ACCOUNTS}; do
           grep ${i} /etc/shadow | awk -F: '($2 != "*") && ($2 !~ "^!") { print $1 }'
         done
      register: service_acc_check
      changed_when: service_acc_check.stdout|length > 0
      notify: Lock service accounts
      failed_when: false

    - meta: flush_handlers